<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DetailSiswa extends Model
{
    use HasFactory;
    protected $table = 'm_detail_siswa';
    protected $primaryKey = 'id';
    protected $fillable = [
        'nama_lengkap',
        'nama_panggilan',
        'foto',
        'foto_after',
        'nisn',
        'nik',
        'nis',
        'gender',
        'rombel',
        'ttl',
        'agama',
        'kewarganegaraan',
        'anak_ke',
        'jml_saudara_kandung',
        'jml_saudara_angkat',
        'jml_saudara_tiri',
        'is_yatim',
        'bahasa',
        'alamat',
        'telp',
        'tinggal',
        'jarak_tinggal',
        'goldar',
        'penyakit_bawaan',
        'kelainan_jasmani',
        'tb',
        'tamatan_dari',
        'tgl_no_ijazah',
        'lama_belajar',
        'dari_sekolah',
        'alasan_pindah',
        'diterima_dikelas',
        'diterima_jurusan',
        'diterima_date',
        'nama_ayah',
        'ttl_ayah',
        'agama_ayah',
        'kewarganegaraan_ayah',
        'pendidikan_ayah',
        'pekerjaan_ayah',
        'penghasilan_ayah',
        'alamat_no_ayah',
        'is_ayah_alive',
        'nama_ibu',
        'ttl_ibu',
        'agama_ibu',
        'kewarganegaraan_ibu',
        'pendidikan_ibu',
        'pekerjaan_ibu',
        'penghasilan_ibu',
        'alamat_no_ibu',
        'is_ibu_alive',
        'nama_wali',
        'ttl_wali',
        'agama_wali',
        'kewarganegaraan_wali',
        'pendidikan_wali',
        'pekerjaan_wali',
        'penghasilan_wali',
        'alamat_no_wali',
        'kesenian',
        'olahraga',
        'organisasi',
        'lain_lain',
        'beasiswa_tahun',
        'beasiswa_kelas',
        'beasiswa_dari',
        'meninggalkan_tahun',
        'meninggalkan_alasan',
        'akhir_tahun',
        'akhir_no_ijazah',
        'akhir_no_stl',
        'akhir_nilai_avg',
        'melanjutkan',
        'bekerja',
    ];
}
